[package]
name = "boxcars-frames"
version = "0.1.0"
edition = "2021"

[dependencies]
boxcars = { git = "https://github.com/IvanMalison/boxcars.git" }
float-ord = "0.3.2"
glam = "0.23.0"
lazy_static = "1.4.0"
log = "0.4.17"
ndarray = "0.15.6"
num-traits = "0.2"
paste = "1.0.12"
serde = { version = "1", features = ["derive"] }

[[bin]]
name = "main"
