[package]
name = "subtr-actor"
version = "0.1.0"
edition = "2021"

[dependencies]
boxcars = "0.9.9"
derive-new = "0.5.9"
float-ord = "0.3.2"
glam = "0.23.0"
lazy_static = "1.4.0"
log = "0.4.17"
ndarray = "0.15.6"
paste = "1.0.12"
serde = { version = "1", features = ["derive"] }
thiserror = "1.0.40"
